apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.frontend.name}}
  name: {{ .Values.frontend.name}}
  namespace: {{ .Values.frontend.namespace}}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name}}
    spec:
      containers:
      - image: {{ .Values.frontend.image.repository}}
        name: {{ .Values.frontend.name}}
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.backend.name}}
  name: {{ .Values.backend.name}} 
  namespace: {{ .Values.backend.namespace}}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name}}
    spec:
      containers:
      - image: {{ .Values.backend.image.repository}}
        name: {{ .Values.backend.name}}
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123"

