apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.hpa.name}}
  namespace: {{ .Values.hpa.namespace}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.hpa.name}}
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30


